[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
optimizer = true
optimizer-runs = 10_000
gas_reports = ["Counter"]

[rpc_endpoints]
sepolia = "${SEPOLIA_KEY}"
mumbai = "${MUMBAI_KEY}"
mainnet = "${MAINNET_KEY}"

[etherscan]
mainnet= { key = "${ETHERSCAN_KEY}" }
sepolia = { key = "${ETHERSCAN_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
